const app=firebase.initializeApp(window.AURA_FIREBASE_CONFIG);const auth=firebase.auth();const db=firebase.firestore();
let me=null,usersData=[],hosts=[],penalties=[],salaries=[],archives=[],quotaDraft=null,selectedUser=null,unsubs=[];let currentCycle={number:1};let settings={weeklyPenalty:20,finishPenalty:5};
const PERMS=['manageUsers','manageHosts','resetCycle','manageReports','managePenalties','manageSettings','manageSalary','manageChat'];
const PERM_LABEL={manageUsers:'Kullanıcı yönetimi',manageHosts:'Yayıncı yönetimi',resetCycle:'Haftalık döngüyü sıfırlama',manageReports:'Rapor yönetimi',managePenalties:'Ceza yönetimi',manageSettings:'Genel ayarlar',manageSalary:'Maaş yönetimi',manageChat:'Chat yönetimi'};
const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('tr-TR').format(Number(n||0)),money=n=>Number(n||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function isManager(){return me&&['admin','ceo'].includes(me.role)}function can(k){return me?.role==='admin'||(me?.role==='ceo'&&me?.permissions?.[k]===true)}
function avatarPlaceholder(name='A'){const c=(String(name).trim()[0]||'A').toUpperCase();const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><rect width="100%" height="100%" rx="80" fill="#6f43dc"/><text x="50%" y="56%" dominant-baseline="middle" text-anchor="middle" font-family="Arial" font-size="72" font-weight="700" fill="white">${c}</text></svg>`;return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`}
async function doLogin(){try{await auth.signInWithEmailAndPassword($('email').value.trim(),$('pass').value)}catch(e){$('loginMsg').textContent='Giriş başarısız: '+(e.code||e.message)}}
async function doLogout(){unsubs.forEach(u=>u&&u());unsubs=[];await auth.signOut()}
auth.onAuthStateChanged(async u=>{if(!u){me=null;$('login').classList.remove('hide');$('app').classList.add('hide');return}try{const d=await db.collection('users').doc(u.uid).get();if(!d.exists)throw Error('Firestore users kaydı yok');me={uid:u.uid,email:u.email,...d.data()};$('login').classList.add('hide');$('app').classList.remove('hide');$('uname').textContent=me.name||u.email;$('urole').textContent=(me.role||'assistant').toUpperCase();document.querySelectorAll('.manager').forEach(x=>x.style.display=isManager()?'':'none');syncOwnProfileUI();await ensureCycle();startLive();updateFinishWindow()}catch(e){$('loginMsg').textContent=e.message;await auth.signOut()}});
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(b.dataset.s).classList.add('on')});
async function ensureCycle(){const ref=db.collection('cycles').doc('current'),d=await ref.get();if(d.exists)currentCycle={...currentCycle,...d.data()};else if(me.role==='admin'){await ref.set({number:1,startedAt:firebase.firestore.FieldValue.serverTimestamp()});currentCycle={number:1}}$('cycleLabel').textContent=`${currentCycle.number||1}. Haftalık Döngü`}
function startLive(){unsubs.forEach(u=>u&&u());unsubs=[];let hq=db.collection('hosts');if(me.role==='assistant')hq=hq.where('ownerUid','==',me.uid);unsubs.push(hq.onSnapshot(s=>{hosts=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>Number(x.cycleNumber||1)===Number(currentCycle.number||1));renderHosts();renderStats();renderSelected()}));if(isManager()){unsubs.push(db.collection('users').onSnapshot(s=>{usersData=s.docs.map(d=>({uid:d.id,...d.data()}));renderUsers();renderSelected();syncGeneralChatMembers()}));unsubs.push(db.collection('penalties').orderBy('createdAt','desc').limit(250).onSnapshot(s=>{penalties=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>Number(x.cycleNumber||1)===Number(currentCycle.number||1));renderPens();renderStats();renderSelected()}));unsubs.push(db.collection('salary').orderBy('createdAt','desc').limit(250).onSnapshot(s=>{salaries=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>Number(x.cycleNumber||1)===Number(currentCycle.number||1));renderSelected()}));unsubs.push(db.collection('reports').where('type','==','cycleArchive').orderBy('closedAt','desc').limit(100).onSnapshot(s=>{archives=s.docs.map(d=>({id:d.id,...d.data()}));renderArchives()}))}else{unsubs.push(db.collection('penalties').where('assistantUid','==',me.uid).onSnapshot(s=>{penalties=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>Number(x.cycleNumber||1)===Number(currentCycle.number||1));renderStats()}));unsubs.push(db.collection('salary').where('assistantUid','==',me.uid).onSnapshot(s=>{salaries=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>Number(x.cycleNumber||1)===Number(currentCycle.number||1));renderSalary()}))}unsubs.push(db.collection('settings').doc('global').onSnapshot(d=>{if(d.exists)settings={...settings,...d.data()};$('weeklyPenalty').value=settings.weeklyPenalty||20;$('finishPenalty').value=settings.finishPenalty||5}));listenChat();checkTodayWorkEnd();if(isManager())setTimeout(checkMissedFinishPenalties,1200)}
async function addHost(){if(!$('hName').value.trim()||!$('hId').value.trim())return alert('İsim ve ID gerekli');await db.collection('hosts').add({ownerUid:me.uid,cycleNumber:currentCycle.number||1,name:$('hName').value.trim(),soyoId:$('hId').value.trim(),phone:$('hPhone').value.trim(),quota:Number($('hQuota').value||0),status:'Aktif',createdAt:firebase.firestore.FieldValue.serverTimestamp()});$('hName').value=$('hId').value=$('hPhone').value=$('hQuota').value=''}
async function delHost(id){if(confirm('Yayıncı silinsin mi?'))await db.collection('hosts').doc(id).delete()}
function openWhats(p){p=String(p||'').replace(/\D/g,'');if(p)location.href='https://wa.me/'+p}
function renderHosts(){$('hostList').innerHTML=hosts.length?hosts.map(h=>`<div class="item"><div class="row"><div><b>${esc(h.name)}</b><div class="muted">ID ${esc(h.soyoId)} • ${esc(h.phone||'')}</div></div><button class="btn red" onclick="delHost('${h.id}')">Sil</button></div><div style="margin-top:8px">Kota: <b>${fmt(h.quota)}</b> 💎 • ${money(Number(h.quota||0)/22000)} USD</div><div class="actions" style="margin-top:8px"><button class="btn green" onclick="openWhats('${esc(h.phone||'')}')">WhatsApp</button></div></div>`).join(''):'<div class="muted">Bu hafta yayıncı yok.</div>'}
function parseQ(x){x=String(x).trim().replace(/\s/g,'');if(!x)return 0;if((x.match(/\./g)||[]).length>1)x=x.replace(/\./g,'');else if(/^\d{1,3}(\.\d{3})+$/.test(x))x=x.replace(/\./g,'');x=x.replace(',','.');return Number(x)||0}
function calcQuota(){const vals=$('qInput').value.split(/\n/).map(parseQ).filter(x=>x>0),total=vals.reduce((a,b)=>a+b,0);quotaDraft={vals,total,usd:total/22000};showQuotaDraft()}
function calcFromCards(){const vals=hosts.map(h=>Number(h.quota||0)).filter(x=>x>0),total=vals.reduce((a,b)=>a+b,0);quotaDraft={vals,total,usd:total/22000};$('qInput').value=vals.join('\n');showQuotaDraft();document.querySelector('[data-s="quota"]').click()}
function showQuotaDraft(){const t=quotaDraft?.total||0;$('qTotal').textContent=fmt(t);$('qUsd').textContent=money(quotaDraft?.usd||0)+' USD';$('qMsg').textContent=t>=100000000?'ELITE • 100M hedef tamamlandı':t>=40000000?'Başarılı • 40M minimum tamamlandı':'40M minimum hedefin altında'}
async function saveQuota(){if(!quotaDraft)return alert('Önce hesapla');await db.collection('reports').add({ownerUid:me.uid,cycleNumber:currentCycle.number||1,type:'quota',quota:quotaDraft.total,usd:quotaDraft.usd,count:quotaDraft.vals.length,createdAt:firebase.firestore.FieldValue.serverTimestamp()});alert('Haftalık rapora kaydedildi')}
function renderStats(){const tq=hosts.reduce((a,h)=>a+Number(h.quota||0),0),usd=tq/22000,pen=penalties.filter(p=>me.role==='assistant'?p.assistantUid===me.uid:true).reduce((a,p)=>a+Number(p.amount||0),0);$('stHosts').textContent=hosts.length;$('stQuota').textContent=fmt(tq);$('stUsd').textContent=money(usd)+' USD';$('stPen').textContent=money(pen)+' AZN';$('p40').style.width=Math.min(100,tq/40000000*100)+'%';$('p100').style.width=Math.min(100,tq/100000000*100)+'%';$('goalMsg').textContent=tq>=100000000?'🟢 Maksimum hedef tamamlandı':tq>=40000000?'🟡 Minimum hedef tamamlandı':'🔴 Minimum hedefe '+fmt(Math.max(0,40000000-tq))+' kaldı'}
function renderUsers(){$('users').innerHTML=usersData.map(u=>`<div class="item" onclick="selectUser('${u.uid}')"><div class="row"><div style="display:flex;gap:10px;align-items:center"><img class="avatar" src="${u.photoDataUrl||avatarPlaceholder(u.name||u.email)}"><div><b>${esc(u.name||u.email||u.uid)}</b><div class="muted">${esc(u.email||'')} • ${esc(u.role||'assistant')}</div></div></div><div class="actions">${me.role==='admin'&&u.uid!==me.uid?`<select onclick="event.stopPropagation()" style="width:115px" onchange="setRole('${u.uid}',this.value)"><option value="assistant" ${u.role==='assistant'?'selected':''}>Asistan</option><option value="ceo" ${u.role==='ceo'?'selected':''}>CEO</option></select>${u.role==='ceo'?`<button class="btn secondary" onclick="event.stopPropagation();openPerms('${u.uid}')">Yetki</button>`:''}`:''}</div></div></div>`).join('');const opts=usersData.filter(u=>u.role!=='admin').map(u=>`<option value="${u.uid}">${esc(u.name||u.email||u.uid)}</option>`).join('');$('penUser').innerHTML=opts;$('salaryUser').innerHTML=opts}
async function setRole(uid,role){if(me.role!=='admin')return;await db.collection('users').doc(uid).update({role,permissions:{}})}
function selectUser(uid){selectedUser=usersData.find(x=>x.uid===uid);renderSelected()}function renderSelected(){if(!selectedUser)return;selectedUser=usersData.find(x=>x.uid===selectedUser.uid)||selectedUser;const uh=hosts.filter(h=>h.ownerUid===selectedUser.uid),up=penalties.filter(p=>p.assistantUid===selectedUser.uid),us=salaries.filter(s=>s.assistantUid===selectedUser.uid),q=uh.reduce((a,h)=>a+Number(h.quota||0),0),p=up.reduce((a,x)=>a+Number(x.amount||0),0),sal=us.reduce((a,x)=>a+Number(x.amount||0),0);$('assistantDetail').innerHTML=`<div class="profile-head"><img class="avatar big" src="${selectedUser.photoDataUrl||avatarPlaceholder(selectedUser.name||selectedUser.email)}"><div><h3>${esc(selectedUser.name||selectedUser.email)}</h3><div class="muted">${esc(selectedUser.email||'')} • ${esc(selectedUser.phone||'')} • ${esc(selectedUser.role||'assistant')}</div></div></div><div class="stats" style="margin-top:12px"><div class="stat"><b>${uh.length}</b><span>Yayıncı</span></div><div class="stat"><b>${fmt(q)}</b><span>Kota</span></div><div class="stat"><b>${money(p)}</b><span>Ceza</span></div><div class="stat"><b>${money(sal)}</b><span>Maaş</span></div></div><h3>Bu Haftanın Yayıncıları</h3>${uh.map(h=>`<div class="item"><b>${esc(h.name)}</b> • ${fmt(h.quota)} 💎</div>`).join('')||'<div class="muted">Yayıncı yok.</div>'}`}
function openCreateUser(){if(me.role!=='admin'&&!can('manageUsers'))return alert('Yetkin yok');$('userModal').classList.remove('hide')}function closeCreateUser(){$('userModal').classList.add('hide')}
async function createUserAccount(){const name=$('newName').value.trim(),em=$('newEmail').value.trim(),pw=$('newPass').value,phone=$('newPhone').value.trim(),role=$('newRole').value;if(!name||!em||pw.length<6)return $('newUserMsg').textContent='Ad, e-posta ve en az 6 karakter şifre gerekli.';let sec;try{sec=firebase.initializeApp(window.AURA_FIREBASE_CONFIG,'secondary-'+Date.now());const sa=sec.auth(),c=await sa.createUserWithEmailAndPassword(em,pw);await db.collection('users').doc(c.user.uid).set({name,email:em,phone,role,permissions:{},photoDataUrl:'',createdAt:firebase.firestore.FieldValue.serverTimestamp()});await sa.signOut();await sec.delete();$('newUserMsg').textContent='✅ Hesap oluşturuldu.';$('newName').value=$('newEmail').value=$('newPhone').value=$('newPass').value='';setTimeout(closeCreateUser,700)}catch(e){$('newUserMsg').textContent='Hata: '+(e.code||e.message);try{if(sec)await sec.delete()}catch(_){}}}
let permUid=null;function openPerms(uid){if(me.role!=='admin')return;permUid=uid;const u=usersData.find(x=>x.uid===uid);$('permList').innerHTML=PERMS.map(k=>`<div class="perm"><span>${PERM_LABEL[k]}</span><input type="checkbox" data-p="${k}" ${u?.permissions?.[k]?'checked':''}></div>`).join('');$('permModal').classList.remove('hide')}function closePerms(){$('permModal').classList.add('hide');permUid=null}async function savePerms(){if(!permUid)return;const p={};document.querySelectorAll('#permList [data-p]').forEach(x=>p[x.dataset.p]=x.checked);await db.collection('users').doc(permUid).update({permissions:p});closePerms()}
async function addPenalty(){if(!can('managePenalties'))return alert('Yetkin yok');if(!$('penUser').value)return;await db.collection('penalties').add({assistantUid:$('penUser').value,amount:Number($('penAmount').value||0),reason:$('penReason').value.trim()||'Ek ceza',cycleNumber:currentCycle.number||1,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:me.uid});$('penReason').value=''}
function renderPens(){$('pens').innerHTML=penalties.length?penalties.slice(0,30).map(p=>{const u=usersData.find(x=>x.uid===p.assistantUid);return`<div class="item"><b>${esc(u?.name||p.assistantUid)}</b><div>${money(p.amount)} AZN • ${esc(p.reason||'')}</div></div>`}).join(''):'<div class="muted">Bu hafta ceza yok.</div>'}
async function saveSettings(){if(!can('manageSettings'))return alert('Yetkin yok');await db.collection('settings').doc('global').set({weeklyPenalty:Number($('weeklyPenalty').value||20),finishPenalty:Number($('finishPenalty').value||5)},{merge:true});alert('Ayarlar kaydedildi')}
async function resetCycle(){if(!can('resetCycle'))return alert('Yetkin yok');if(!confirm('Mevcut haftayı sonlandırıp arşivlemek ve yeni haftayı 0 aktif veriyle başlatmak istiyor musun?'))return;const oldCycle=Number(currentCycle.number||1),snap=await db.collection('users').get(),all=snap.docs.map(d=>({uid:d.id,...d.data()}));for(const u of all.filter(x=>x.role!=='admin')){const uh=hosts.filter(h=>h.ownerUid===u.uid),up=penalties.filter(p=>p.assistantUid===u.uid),us=salaries.filter(x=>x.assistantUid===u.uid);await db.collection('reports').add({ownerUid:u.uid,type:'cycleArchive',cycleNumber:oldCycle,assistantName:u.name||u.email,hostCount:uh.length,quota:uh.reduce((a,h)=>a+Number(h.quota||0),0),penalty:up.reduce((a,p)=>a+Number(p.amount||0),0),salary:us.reduce((a,x)=>a+Number(x.amount||0),0),closedAt:firebase.firestore.FieldValue.serverTimestamp(),closedBy:me.uid})}await db.collection('cycles').doc('current').set({number:oldCycle+1,startedAt:firebase.firestore.FieldValue.serverTimestamp(),previousCycle:oldCycle});currentCycle.number=oldCycle+1;hosts=[];penalties=[];salaries=[];quotaDraft=null;$('cycleLabel').textContent=`${currentCycle.number}. Haftalık Döngü`;renderHosts();renderPens();renderSalary();renderStats();renderSelected();startLive();alert('✅ Eski hafta arşivlendi. Yeni hafta 0 aktif veriyle başladı.')}
function renderArchives(){$('archiveList').innerHTML=archives.length?archives.map(a=>`<div class="item archive"><div class="row"><div><b>${esc(a.assistantName||a.ownerUid)}</b><div class="muted">${a.cycleNumber}. hafta</div></div><span class="badge">Arşiv</span></div><div style="margin-top:8px">Yayıncı: ${a.hostCount||0} • Kota: ${fmt(a.quota)} • Ceza: ${money(a.penalty)} AZN • Maaş: ${money(a.salary)} AZN</div></div>`).join(''):'<div class="muted">Henüz kapatılmış hafta yok.</div>'}
function updateFinishWindow(){const h=new Date().getHours(),ok=h===5;$('finishBtn').disabled=!ok;$('finishInfo').textContent=ok?'✅ Saat 05:00–05:59. Kapanış yapabilirsin.':'⏳ Buton yalnızca 05:00–05:59 arasında aktif.';setTimeout(updateFinishWindow,60000)}function dayKey(d=new Date()){return d.toISOString().slice(0,10)}
async function finishWork(){if(new Date().getHours()!==5)return alert('Sadece 05:00–05:59 arasında kullanılabilir');await db.collection('workEnd').doc(`${me.uid}_${dayKey()}`).set({assistantUid:me.uid,date:dayKey(),finishedAt:firebase.firestore.FieldValue.serverTimestamp(),cycleNumber:currentCycle.number||1});checkTodayWorkEnd();alert('İş bitirme kaydedildi 🌙')}
async function checkTodayWorkEnd(){if(!me)return;const d=await db.collection('workEnd').doc(`${me.uid}_${dayKey()}`).get();$('workToday').textContent=d.exists?'✅ Bugünkü iş bitirme kaydın var.':'Bugün henüz iş bitirme kaydı yok.'}
async function checkMissedFinishPenalties(){if(!can('managePenalties'))return;const now=new Date();if(now.getHours()<6)return;const yesterday=new Date(now);yesterday.setDate(now.getDate()-1);const key=dayKey(yesterday);for(const u of usersData.filter(x=>['assistant','ceo'].includes(x.role))){const wd=await db.collection('workEnd').doc(`${u.uid}_${key}`).get(),pid=`finish_${u.uid}_${key}`,pd=await db.collection('penalties').doc(pid).get();if(!wd.exists&&!pd.exists)await db.collection('penalties').doc(pid).set({assistantUid:u.uid,amount:Number(settings.finishPenalty||5),reason:'05:00 iş bitirme yapılmadı',date:key,auto:true,cycleNumber:currentCycle.number||1,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:me.uid})}}
async function fileToDataUrl(file,max=900,quality=.58){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const sc=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*sc);c.height=Math.round(img.height*sc);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',quality))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function addSalary(){if(!can('manageSalary'))return alert('Yetkin yok');if(!$('salaryUser').value||!$('salaryAmount').value)return alert('Kullanıcı ve tutar gerekli');let proof='';const f=$('salaryProof').files[0];if(f)proof=await fileToDataUrl(f,1000,.55);if(proof.length>700000)return alert('Fotoğraf çok büyük.');await db.collection('salary').add({assistantUid:$('salaryUser').value,amount:Number($('salaryAmount').value),note:$('salaryNote').value.trim(),proofDataUrl:proof,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:me.uid,cycleNumber:currentCycle.number||1});$('salaryAmount').value=$('salaryNote').value='';$('salaryProof').value='';alert('Maaş kaydı eklendi')}
function renderSalary(){$('salaryList').innerHTML=salaries.length?salaries.map(s=>`<div class="item"><b>${money(s.amount)} AZN</b><div>${esc(s.note||'')}</div>${s.proofDataUrl?`<img class="proof" src="${s.proofDataUrl}">`:''}</div>`).join(''):'<div class="muted">Bu hafta maaş kaydı yok.</div>'}
function syncOwnProfileUI(){if(!me)return;$('profileName').value=me.name||'';$('profilePhone').value=me.phone||'';$('profileEmail').textContent=me.email||'';$('profileRole').textContent=(me.role||'assistant').toUpperCase();const pic=me.photoDataUrl||avatarPlaceholder(me.name||me.email);$('topAvatar').src=pic;$('profileAvatar').src=pic}
async function saveProfileSettings(){let photo=me.photoDataUrl||'';const f=$('profilePhoto').files[0];if(f){photo=await fileToDataUrl(f,500,.5);if(photo.length>300000)return alert('Profil fotoğrafı çok büyük.')}const payload={name:$('profileName').value.trim()||me.name||'',phone:$('profilePhone').value.trim(),photoDataUrl:photo};await db.collection('users').doc(me.uid).update(payload);me={...me,...payload};$('profilePhoto').value='';$('uname').textContent=me.name||me.email;syncOwnProfileUI();alert('Profil güncellendi')}
async function changeOwnPassword(){const oldp=$('oldPassword').value,np1=$('newPassword1').value,np2=$('newPassword2').value;if(!oldp||np1.length<6)return $('passwordInfo').textContent='Mevcut şifre ve en az 6 karakter yeni şifre gerekli.';if(np1!==np2)return $('passwordInfo').textContent='Yeni şifreler aynı değil.';try{const cred=firebase.auth.EmailAuthProvider.credential(auth.currentUser.email,oldp);await auth.currentUser.reauthenticateWithCredential(cred);await auth.currentUser.updatePassword(np1);$('oldPassword').value=$('newPassword1').value=$('newPassword2').value='';$('passwordInfo').textContent='✅ Şifre başarıyla değiştirildi.'}catch(e){$('passwordInfo').textContent='Hata: '+(e.code||e.message)}}
async function syncGeneralChatMembers(){if(!isManager()||!usersData.length)return;await db.collection('chats').doc('general').set({name:'Genel Chat',memberUids:usersData.map(u=>u.uid),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}
function listenChat(){unsubs.push(db.collection('chats').doc('general').collection('messages').orderBy('createdAt','asc').limitToLast(100).onSnapshot(s=>{$('chatBox').innerHTML=s.docs.map(d=>{const x=d.data();return`<div class="msg ${x.senderUid===me.uid?'mine':''}"><b>${esc(x.senderName||'')}</b><div>${esc(x.text||'')}</div></div>`}).join('');$('chatBox').scrollTop=$('chatBox').scrollHeight},()=>{$('chatBox').innerHTML='<div class="muted">Chat henüz hazır değil.</div>'}))}
async function sendChat(){const t=$('chatInput').value.trim();if(!t)return;await db.collection('chats').doc('general').collection('messages').add({senderUid:me.uid,senderName:me.name||me.email,text:t,createdAt:firebase.firestore.FieldValue.serverTimestamp()});$('chatInput').value=''}