let adSubmissions=[],announcements=[],rankingsData=[],pendingInitialized=false,knownPending=new Set();
['manageAds','manageAnnouncements','manageRankings'].forEach(k=>{if(!PERMS.includes(k))PERMS.push(k)});Object.assign(PERM_LABEL,{manageAds:'Reklam kanıtı onaylama',manageAnnouncements:'Duyuru yayınlama',manageRankings:'Sıralama yayınlama'});

document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.sec').forEach(x=>x.classList.remove('on'));b.classList.add('on');const s=document.getElementById(b.dataset.s);if(s)s.classList.add('on')});
auth.onAuthStateChanged(u=>setTimeout(()=>document.querySelectorAll('.mgr').forEach(x=>x.style.display=u&&isManager()?'':'none'),0));

/* Core chat override: installed BEFORE startLive runs so delete buttons are always present. */
function canDeleteGeneralMessage(x){return !!me&&(me.role==='admin'||(me.role==='ceo'&&me.permissions?.manageChat===true)||x.senderUid===me.uid)}
window.deleteChatMessage=async function(id){if(!id||!confirm('Bu mesaj silinsin mi?'))return;try{await db.collection('chats').doc('general').collection('messages').doc(id).delete()}catch(e){alert('Mesaj silinemedi: '+(e.code||e.message))}};
listenChat=function(){unsubs.push(db.collection('chats').doc('general').collection('messages').orderBy('createdAt','asc').limitToLast(100).onSnapshot(s=>{const box=$('chatBox');if(!box)return;box.innerHTML=s.docs.map(d=>{const x=d.data(),del=canDeleteGeneralMessage(x)?`<button class="btn r" style="padding:5px 8px;font-size:11px" onclick="deleteChatMessage('${d.id}')">Sil</button>`:'';return `<div class="msg ${x.senderUid===me.uid?'mine':''}"><div class="row"><b>${esc(x.senderName||'')}</b>${del}</div><div>${esc(x.text||'')}</div></div>`}).join('')||'<div class="muted">Henüz mesaj yok.</div>';box.scrollTop=box.scrollHeight},e=>{const box=$('chatBox');if(box)box.innerHTML='<div class="muted">Chat yüklenemedi: '+esc(e.code||e.message)+'</div>'}))};

const _v3StartLive=startLive;startLive=function(){_v3StartLive();listenAds();listenAnnouncements();listenRankings()};
function statusLabel(s){return({pending:'Admin Onayı Bekliyor',approved:'Onaylandı',rejected:'Reddedildi',none:'Gönderilmedi'})[s]||'Gönderilmedi'}
function statusClass(s){return s==='approved'?'status-approved':s==='rejected'?'status-rejected':s==='pending'?'status-pending':''}
function adDocId(n){return `${currentCycle.number||1}_${me.uid}_${n}`}
async function compactImage(file,max=720,q=.45){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const sc=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*sc);c.height=Math.round(img.height*sc);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',q))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function submitAdProof(n){const ref=db.collection('adSubmissions').doc(adDocId(n)),old=await ref.get();if(old.exists&&old.data().status==='approved')return alert('Bu reklam zaten onaylandı.');if(old.exists&&old.data().status==='pending')return alert('Bu reklam zaten admin onayı bekliyor.');const f1=document.getElementById(`ad${n}Proof1`).files[0],f2=document.getElementById(`ad${n}Proof2`).files[0],note=document.getElementById(`ad${n}Note`).value.trim(),amount=document.getElementById(`ad${n}Amount`).value.trim();if(!f1||!f2)return alert('İki ayrı kanıt SS zorunlu.');if(note.length<10)return alert('Açıklama alanına reklam detayını yaz.');const [p1,p2]=await Promise.all([compactImage(f1),compactImage(f2)]);if(p1.length+p2.length>780000)return alert('Kanıtlar çok büyük. Daha küçük ekran görüntüsü seç.');await ref.set({assistantUid:me.uid,assistantName:me.name||me.email,cycleNumber:currentCycle.number||1,adNumber:n,amountInfo:amount,note,proof1DataUrl:p1,proof2DataUrl:p2,status:'pending',submittedAt:firebase.firestore.FieldValue.serverTimestamp(),reviewedAt:null,reviewedBy:null,rejectReason:''},{merge:true});alert('✅ Reklam kanıtı admin onayına gönderildi.')}
function listenAds(){let q=db.collection('adSubmissions').where('cycleNumber','==',Number(currentCycle.number||1));if(me.role==='assistant')q=q.where('assistantUid','==',me.uid);unsubs.push(q.onSnapshot(s=>{adSubmissions=s.docs.map(d=>({id:d.id,...d.data()}));renderOwnAds();if(isManager())renderAdReviews()}))}
function renderOwnAds(){[1,2].forEach(n=>{const x=adSubmissions.find(a=>a.assistantUid===me.uid&&Number(a.adNumber)===n),st=x?.status||'none',badge=document.getElementById(`ad${n}Status`),info=document.getElementById(`ad${n}Info`);if(!badge||!info)return;badge.className='ad-status '+statusClass(st);badge.textContent=statusLabel(st);info.innerHTML=x?`${statusLabel(st)}${x.rejectReason?`<br><b>Red sebebi:</b> ${esc(x.rejectReason)}`:''}`:'Henüz gönderilmedi.'})}
function maybeBrowserNotify(pending){if(!isManager())return;const ids=new Set(pending.map(x=>x.id));if(pendingInitialized&&'Notification' in window&&Notification.permission==='granted')pending.forEach(x=>{if(!knownPending.has(x.id))new Notification('Aura Agency • Reklam Onayı',{body:`${x.assistantName||'Asistan'} reklam kanıtını gönderdi.`})});knownPending=ids;pendingInitialized=true}
function renderAdReviews(){const pending=adSubmissions.filter(x=>x.status==='pending'),list=document.getElementById('adReviewList');if(!list)return;const pc=document.getElementById('pendingCount'),pb=document.getElementById('pendingBadge');if(pc)pc.textContent=pending.length;if(pb){pb.textContent=pending.length;pb.classList.toggle('hide',!pending.length)}maybeBrowserNotify(pending);list.innerHTML=pending.map(x=>`<div class="item review-card"><b>${esc(x.assistantName||x.assistantUid)} • ${x.adNumber}. Reklam</b><div>${esc(x.note||'')}</div><div class="proof-grid"><img src="${x.proof1DataUrl}"><img src="${x.proof2DataUrl}"></div><button class="btn g" onclick="reviewAd('${x.id}','approved')">Kabul Et</button> <button class="btn r" onclick="reviewAd('${x.id}','rejected')">Reddet</button></div>`).join('')||'<div class="muted">Bekleyen reklam onayı yok.</div>'}
async function reviewAd(id,status){let rejectReason=status==='rejected'?(prompt('Red sebebi:')||''):'';if(status==='rejected'&&!rejectReason)return;await db.collection('adSubmissions').doc(id).update({status,rejectReason,reviewedAt:firebase.firestore.FieldValue.serverTimestamp(),reviewedBy:me.uid})}
function listenAnnouncements(){unsubs.push(db.collection('announcements').orderBy('createdAt','desc').limit(20).onSnapshot(s=>{announcements=s.docs.map(d=>({id:d.id,...d.data()}));renderAnnouncements()},e=>{const el=document.getElementById('announcementList');if(el)el.innerHTML='<div class="muted">Duyurular yüklenemedi: '+esc(e.code||e.message)+'</div>'}))}
function renderAnnouncements(){const el=document.getElementById('announcementList');if(el)el.innerHTML=announcements.map(x=>`<div class="notice"><b>${esc(x.title||'Duyuru')}</b><div>${esc(x.text||'')}</div></div>`).join('')||'<div class="muted">Henüz duyuru yok.</div>'}
async function publishAnnouncement(){const title=document.getElementById('announceTitle')?.value.trim()||'',text=document.getElementById('announceText')?.value.trim()||'';if(!title||!text)return alert('Başlık ve mesaj gerekli.');if(!(me?.role==='admin'||(me?.role==='ceo'&&me?.permissions?.manageAnnouncements===true)))return alert('Duyuru yayınlama yetkin yok.');try{await db.collection('announcements').add({title,text,createdBy:me.uid,createdByName:me.name||me.email,createdAt:firebase.firestore.FieldValue.serverTimestamp()});document.getElementById('announceTitle').value='';document.getElementById('announceText').value='';alert('✅ Duyuru yayınlandı.')}catch(e){alert('Duyuru yayınlanamadı: '+(e.code||e.message)+'\n\npermission-denied ise yalnızca Firebase Firestore Rules ekranında güncel kuralları Publish etmen gerekir.')}}
function listenRankings(){unsubs.push(db.collection('rankings').where('cycleNumber','==',Number(currentCycle.number||1)).onSnapshot(s=>{rankingsData=s.docs.map(d=>({id:d.id,...d.data()}));renderRankings()}))}
function renderRankings(){const daily=document.getElementById('dailyRankList'),weekly=document.getElementById('weeklyRankList');if(!daily||!weekly)return;const card=x=>`<div class="item"><b>${esc(x.title||'Sıralama')}</b><img class="ranking-img" src="${x.imageDataUrl}"></div>`;daily.innerHTML=rankingsData.filter(x=>x.type==='daily').map(card).join('');weekly.innerHTML=rankingsData.filter(x=>x.type==='weekly').map(card).join('')}
async function publishRanking(){const f=document.getElementById('rankingFile').files[0],type=document.getElementById('rankingType').value,title=document.getElementById('rankingTitle').value.trim();if(!f||!title)return alert('Başlık ve SS gerekli.');const img=await fileToDataUrl(f);await db.collection('rankings').add({type,title,imageDataUrl:img,cycleNumber:currentCycle.number||1,createdBy:me.uid,createdAt:firebase.firestore.FieldValue.serverTimestamp()})}
/* V5 loader */
(()=>{const s=document.createElement('script');s.src='v5-extra.js?v=5.2.0';s.defer=true;document.head.appendChild(s)})();