/* Aura Agency V5 Command Center */
let v5Trash=[],v5Logs=[],v5PenaltySuggestions=[];
function v5Log(action,detail=''){if(!me)return Promise.resolve();return db.collection('auditLogs').add({actorUid:me.uid,actorName:me.name||me.email,action,detail,cycleNumber:currentCycle.number||1,createdAt:firebase.firestore.FieldValue.serverTimestamp()}).catch(()=>{})}
function v5ShowManagers(){if(!isManager())return;document.querySelectorAll('.mgr').forEach(x=>x.style.display='');const nav=document.getElementById('nav');if(nav&&!document.getElementById('v5CommandBtn')){const b=document.createElement('button');b.id='v5CommandBtn';b.className='v5mgr';b.textContent='🛡️ Komuta Merkezi';b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.sec').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.getElementById('command')?.classList.add('on');v5Render()};nav.appendChild(b)}const h=document.querySelector('#app .top h1');if(h)h.textContent='Aura Agency Panel V5'}
const _v5Start=startLive;startLive=function(){_v5Start();setTimeout(()=>{v5ShowManagers();v5Mount()},150);if(isManager()){unsubs.push(db.collection('auditLogs').orderBy('createdAt','desc').limit(100).onSnapshot(s=>{v5Logs=s.docs.map(d=>({id:d.id,...d.data()}));v5Render()}));unsubs.push(db.collection('trash').orderBy('deletedAt','desc').limit(100).onSnapshot(s=>{v5Trash=s.docs.map(d=>({id:d.id,...d.data()}));v5Render()}));unsubs.push(db.collection('penaltySuggestions').where('cycleNumber','==',Number(currentCycle.number||1)).onSnapshot(s=>{v5PenaltySuggestions=s.docs.map(d=>({id:d.id,...d.data()}));v5Render()}))}};
auth.onAuthStateChanged(u=>{if(u)setTimeout(()=>{v5ShowManagers();v5Mount()},900)});
function v5Mount(){if(!isManager())return;v5ShowManagers();if(document.getElementById('command')){v5Render();return}const app=document.getElementById('app');if(!app)return;const sec=document.createElement('section');sec.id='command';sec.className='sec';sec.innerHTML=`<div id="v5suite"><div class="card"><div class="row"><div><h2>🛡️ Admin Komuta Merkezi</h2><div class="muted">Tüm asistanlar, yayıncılar, kota, ceza ve risk durumu tek ekranda.</div></div><button class="btn s" onclick="v5Backup()">Yedek İndir</button></div><div id="v5Health" class="alert"></div><input id="v5Search" placeholder="Asistan, yayıncı, SOYO ID veya telefon ara..." oninput="v5Render()"><div id="v5Command" class="list" style="margin-top:12px"></div></div><div class="grid" style="margin-top:12px"><div class="card"><h2>🏆 Haftalık Liderlik</h2><div id="v5Leaders" class="list"></div></div><div class="card"><h2>⚠️ Risk & Otomatik Ceza Önerileri</h2><button class="btn y" onclick="v5ScanPenalties()">Kuralları Kontrol Et</button><div id="v5Risks" class="list" style="margin-top:10px"></div></div></div><div class="grid" style="margin-top:12px"><div class="card"><h2>🧾 Admin İşlem Geçmişi</h2><div id="v5Audit" class="list"></div></div><div class="card"><h2>🗑️ Çöp Kutusu / Geri Yükle</h2><div id="v5Trash" class="list"></div></div></div><div class="grid" style="margin-top:12px"><div class="card"><h2>📥 CSV ile Yayıncı Aktar</h2><p class="muted">Sütunlar: isim, SOYO ID, telefon, kota.</p><input id="v5Csv" type="file" accept=".csv,text/csv"><button class="btn g" style="margin-top:10px" onclick="v5ImportCsv()">CSV Aktar</button></div><div class="card"><h2>📊 Hızlı Yönetim</h2><p class="muted">Asistan kartlarında durum rengi, yayıncı listesi ve arşivleme bulunur.</p><button class="btn" onclick="document.querySelector('[data-s=\"admin\"]')?.click()">Klasik Yönetim Panelini Aç</button></div></div></div>`;app.appendChild(sec);v5Render()}
function v5AssistantRows(){return usersData.filter(u=>u.role==='assistant'||u.role==='ceo').map(u=>{const hs=hosts.filter(h=>h.ownerUid===u.uid),q=hs.reduce((a,h)=>a+Number(h.quota||0),0),p=penalties.filter(x=>x.assistantUid===u.uid).reduce((a,x)=>a+Number(x.amount||0),0);return{u,hs,q,p}}).sort((a,b)=>b.q-a.q)}
function v5Render(){if(!isManager()||!document.getElementById('v5suite'))return;const rows=v5AssistantRows(),search=(document.getElementById('v5Search')?.value||'').toLowerCase(),filtered=rows.filter(r=>!search||[r.u.name,r.u.email,...r.hs.flatMap(h=>[h.name,h.soyoId,h.phone])].join(' ').toLowerCase().includes(search));const tq=hosts.reduce((a,h)=>a+Number(h.quota||0),0),adOk=(typeof adSubmissions!=='undefined'?adSubmissions.filter(a=>a.status==='approved').length:0),score=Math.max(0,Math.min(100,Math.round(Math.min(tq/40000000,1)*55+Math.min(hosts.length/20,1)*25+Math.min(adOk/2,1)*20)));document.getElementById('v5Health').innerHTML=`<b>Ajans Sağlık Puanı: ${score}/100</b> • ${fmt(tq)} 💎 toplam kota • ${hosts.length} yayıncı • ${adOk}/2 onaylı reklam`;
document.getElementById('v5Leaders').innerHTML=rows.slice(0,10).map((r,i)=>`<div class="item"><b>${i+1}. ${esc(r.u.name||r.u.email)}</b><div>${r.hs.length} yayıncı • ${fmt(r.q)} 💎 • ${money(r.p)} AZN ceza</div></div>`).join('')||'<div class="muted">Henüz asistan verisi yok.</div>';
document.getElementById('v5Command').innerHTML=filtered.map(r=>`<div class="item"><div class="row"><div><b>${esc(r.u.name||r.u.email)}</b><div class="muted">${esc(r.u.email||'')} • ${r.hs.length} yayıncı • ${fmt(r.q)} 💎 • ${money(r.p)} AZN ceza</div></div><span class="tag">${r.q>=40000000?'🟢 İyi':r.q>=20000000?'🟡 Takip':'🔴 Risk'}</span></div><details style="margin-top:9px"><summary style="cursor:pointer;font-weight:800">Yayıncıları ve geçmişi göster</summary><div style="margin-top:8px">${r.hs.map(h=>`<div class="item"><b>${esc(h.name)}</b><div class="muted">SOYO ID ${esc(h.soyoId)} • ${esc(h.phone||'')}</div><div>${fmt(h.quota)} 💎</div><button class="btn r s" style="margin-top:6px" onclick="v5TrashHost('${h.id}')">Çöp Kutusuna Taşı</button></div>`).join('')||'<div class="muted">Bu asistanda yayıncı yok.</div>'}</div></details></div>`).join('')||'<div class="muted">Aramaya uygun sonuç yok.</div>';
document.getElementById('v5Audit').innerHTML=v5Logs.slice(0,30).map(x=>`<div class="item"><b>${esc(x.actorName||'Admin')}</b> • ${esc(x.action||'İşlem')}<div class="muted">${esc(x.detail||'')} ${x.createdAt?.toDate?x.createdAt.toDate().toLocaleString('tr-TR'):''}</div></div>`).join('')||'<div class="muted">Henüz işlem kaydı yok.</div>';
document.getElementById('v5Trash').innerHTML=v5Trash.map(x=>`<div class="item"><div class="row"><b>${esc(x.data?.name||x.type||'Kayıt')}</b><button class="btn g s" onclick="v5Restore('${x.id}')">Geri Yükle</button></div></div>`).join('')||'<div class="muted">Çöp kutusu boş.</div>';
const risks=rows.filter(r=>r.hs.length<20||r.q<40000000);document.getElementById('v5Risks').innerHTML=(risks.map(r=>`<div class="item"><b>${esc(r.u.name||r.u.email)}</b><div class="bad">${r.hs.length<20?'20 yayıncı minimumunun altında. ':''}${r.q<40000000?'40M kota hedefinin altında.':''}</div></div>`).join('')||'<div class="ok">Riskli asistan yok.</div>')+v5PenaltySuggestions.filter(x=>x.status==='pending').map(x=>`<div class="item"><b>Ceza önerisi: ${esc(x.assistantName||'')}</b><div>${money(x.amount)} AZN • ${esc(x.reason)}</div><button class="btn r s" onclick="v5ApprovePenalty('${x.id}')">Admin Onayla</button></div>`).join('')}
async function v5ScanPenalties(){for(const r of v5AssistantRows()){if(r.hs.length<20){const id=`${currentCycle.number}_${r.u.uid}_hosts`;await db.collection('penaltySuggestions').doc(id).set({assistantUid:r.u.uid,assistantName:r.u.name||r.u.email,cycleNumber:currentCycle.number||1,amount:Number(settings.weeklyPenalty||20),reason:'Haftalık minimum 20 yayıncı şartı sağlanmadı',status:'pending',createdAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}}await v5Log('Ceza taraması','Haftalık kurallar kontrol edildi')}
async function v5ApprovePenalty(id){const d=await db.collection('penaltySuggestions').doc(id).get();if(!d.exists)return;const x=d.data();await db.collection('penalties').add({assistantUid:x.assistantUid,amount:Number(x.amount||0),reason:x.reason,cycleNumber:currentCycle.number||1,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:me.uid});await d.ref.update({status:'approved',approvedBy:me.uid,approvedAt:firebase.firestore.FieldValue.serverTimestamp()});await v5Log('Ceza onaylandı',`${x.assistantName||''} • ${x.reason}`)}
async function v5TrashHost(id){const r=db.collection('hosts').doc(id),d=await r.get();if(!d.exists||!confirm('Yayıncı çöp kutusuna taşınsın mı?'))return;await db.collection('trash').add({type:'host',originalId:id,data:d.data(),deletedAt:firebase.firestore.FieldValue.serverTimestamp(),deletedBy:me.uid});await r.delete();await v5Log('Yayıncı arşivlendi',d.data().name||id)}
async function v5Restore(id){const r=db.collection('trash').doc(id),d=await r.get();if(!d.exists)return;const x=d.data();if(x.type==='host'){await db.collection('hosts').doc(x.originalId).set(x.data);await r.delete();await v5Log('Yayıncı geri yüklendi',x.data?.name||x.originalId)}}
function v5Backup(){const payload={version:5,exportedAt:new Date().toISOString(),cycle:currentCycle,users:usersData,hosts,penalties,salaries,archives,ads:typeof adSubmissions!=='undefined'?adSubmissions:[],announcements:typeof announcements!=='undefined'?announcements:[],rankings:typeof rankingsData!=='undefined'?rankingsData:[]};const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`aura-agency-backup-cycle-${currentCycle.number||1}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);v5Log('Yedek indirildi','V5 JSON yedeği')}
async function v5ImportCsv(){const f=document.getElementById('v5Csv').files[0];if(!f)return alert('CSV seç.');const lines=(await f.text()).split(/\r?\n/).filter(Boolean);let n=0;for(let i=0;i<lines.length;i++){const c=lines[i].split(/[,;]/).map(x=>x.trim());if(i===0&&/name|isim/i.test(c[0]))continue;if(!c[0]||!c[1])continue;await db.collection('hosts').add({ownerUid:me.uid,cycleNumber:currentCycle.number||1,name:c[0],soyoId:c[1],phone:c[2]||'',quota:Number(String(c[3]||0).replace(/\./g,''))||0,status:'Aktif',createdAt:firebase.firestore.FieldValue.serverTimestamp()});n++}await v5Log('CSV içe aktarma',`${n} yayıncı`);alert(`${n} yayıncı aktarıldı.`)}
const _v5OldPenalty=addPenalty;addPenalty=async function(){await _v5OldPenalty();v5Log('Manuel ceza','Ceza yönetiminden işlem')};
const _v5OldHost=addHost;addHost=async function(){const name=document.getElementById('hName').value.trim();await _v5OldHost();if(name)v5Log('Yayıncı eklendi',name)};
setInterval(()=>{if(isManager()){v5ShowManagers();v5Render()}},3000);