/* Aura Agency V6 Live: presence, typing, WebRTC voice calls, call history, voice messages */
(function(){
  const V6={presence:{},currentChat:null,msgUnsub:null,chatDocUnsub:null,calls:[],callUnsubs:[],pc:null,localStream:null,activeCall:null,ring:null,rec:null,recStream:null,recTimer:null};
  window.AuraV6=V6;
  const ts=()=>firebase.firestore.FieldValue.serverTimestamp();
  const userName=uid=>{const u=(usersData||[]).find(x=>x.uid===uid);return u?.name||u?.email||uid};
  const online=uid=>{const p=V6.presence[uid];if(!p)return false;const d=p.lastSeen?.toDate?.();return p.online===true&&(!d||Date.now()-d.getTime()<90000)};
  const lastSeenText=uid=>{const p=V6.presence[uid];if(online(uid))return '🟢 Online';const d=p?.lastSeen?.toDate?.();return d?'⚪ Son görülme '+d.toLocaleString('tr-TR'):'⚪ Offline'};

  function injectCss(){if(document.getElementById('v6css'))return;const s=document.createElement('style');s.id='v6css';s.textContent=`
  .v6-status{font-size:12px;margin-top:3px}.v6-online{color:#48df9b}.v6-offline{opacity:.72}.v6-call-modal{position:fixed;inset:0;background:#090512d9;display:flex;align-items:center;justify-content:center;z-index:99999;padding:18px}.v6-call-card{width:min(430px,96vw);background:#1b102e;border:1px solid #6f43dc66;border-radius:28px;padding:28px;text-align:center;box-shadow:0 30px 90px #0008}.v6-call-avatar{width:92px;height:92px;border-radius:50%;object-fit:cover;margin:0 auto 14px;border:3px solid #8d5cff}.v6-call-actions{display:flex;gap:12px;justify-content:center;margin-top:22px}.v6-call-actions .btn{min-width:120px}.v6-pulse{animation:v6pulse 1.3s infinite}@keyframes v6pulse{50%{transform:scale(1.05);box-shadow:0 0 0 14px #8d5cff18}}.v6-typing{min-height:20px;font-size:12px;margin:6px 2px}.v6-audio{width:min(320px,100%);margin-top:6px}.v6-rec{background:#8b2348!important}.v6-call-row{display:flex;justify-content:space-between;gap:10px;align-items:center}.v6-dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:#46dd91;margin-right:6px}`;document.head.appendChild(s)}

  async function setPresence(state=true){if(!me)return;try{await db.collection('presence').doc(me.uid).set({uid:me.uid,name:me.name||me.email,role:me.role,online:state,lastSeen:ts()},{merge:true})}catch(_){}}
  function startPresence(){setPresence(true);clearInterval(window.__v6Presence);window.__v6Presence=setInterval(()=>setPresence(true),30000);unsubs.push(db.collection('presence').onSnapshot(s=>{V6.presence={};s.forEach(d=>V6.presence[d.id]=d.data());if(typeof renderAssistantManager==='function')renderAssistantManager();renderPrivatePresence()}));window.addEventListener('beforeunload',()=>setPresence(false));document.addEventListener('visibilitychange',()=>setPresence(document.visibilityState==='visible'))}

  function renderPrivatePresence(){if(!V6.currentChat)return;const c=V6.privateChats?.find(x=>x.id===V6.currentChat),other=(c?.memberUids||[]).find(x=>x!==me.uid),el=document.getElementById('v6PrivatePresence');if(el&&other)el.textContent=lastSeenText(other)}

  const oldRenderAssistant=window.renderAssistantManager;
  window.renderAssistantManager=function(){
    const el=document.getElementById('v5AssistantManager');if(!el){if(oldRenderAssistant)oldRenderAssistant();return}
    const rows=(usersData||[]).filter(u=>['assistant','ceo'].includes(u.role));
    el.innerHTML=`<div class="row"><div><h2>👥 Asistan Yönetimi</h2><div class="muted">Canlı durum, özel mesaj, sesli arama ve hesap yönetimi.</div></div></div><div class="list" style="margin-top:10px">${rows.map(u=>`<div class="item"><div class="row"><div><b>${esc(u.name||u.email)}</b><div class="muted">${esc(u.email||'')} • ${esc(u.role||'assistant')}</div><div class="v6-status ${online(u.uid)?'v6-online':'v6-offline'}">${lastSeenText(u.uid)}</div></div><div class="actions"><button class="btn g s" onclick="openPrivateChatWith('${u.uid}')">💬 Mesaj</button><button class="btn s" onclick="startVoiceCall('${u.uid}')">📞 Ara</button>${me.role==='admin'?`<button class="btn r s" onclick="deleteAssistantV5('${u.uid}')">🗑️ Sil</button>`:''}</div></div></div>`).join('')||'<div class="muted">Asistan yok.</div>'}</div>`;
  };

  const oldOpen=window.openPrivateChatWith;
  window.openPrivateChatWith=async function(uid){await oldOpen(uid);setTimeout(()=>{if(V6.currentChat)selectPrivateChat(V6.currentChat)},150)};

  window.selectPrivateChat=function(id){
    V6.currentChat=id;document.querySelectorAll('[data-private-chat]').forEach(x=>x.classList.toggle('on',x.dataset.privateChat===id));
    if(V6.msgUnsub)V6.msgUnsub();if(V6.chatDocUnsub)V6.chatDocUnsub();
    const box=document.getElementById('privateChatBox');if(box)box.innerHTML='<div class="muted">Mesajlar yükleniyor...</div>';
    V6.msgUnsub=db.collection('chats').doc(id).collection('messages').orderBy('createdAt','asc').limitToLast(100).onSnapshot(s=>{if(!box)return;box.innerHTML=s.docs.map(d=>{const x=d.data(),mine=x.senderUid===me.uid,del=(me.role==='admin'||(me.role==='ceo'&&me.permissions?.manageChat)||mine)?`<button class="btn r" style="padding:4px 7px;font-size:11px" onclick="deletePrivateMessage('${id}','${d.id}')">Sil</button>`:'';const body=x.type==='audio'&&x.audioDataUrl?`<audio class="v6-audio" controls src="${x.audioDataUrl}"></audio>`:`<div>${esc(x.text||'')}</div>`;return `<div class="msg ${mine?'mine':''}"><div class="row"><b>${esc(x.senderName||'')}</b>${del}</div>${body}</div>`}).join('')||'<div class="muted">Henüz mesaj yok.</div>';box.scrollTop=box.scrollHeight});
    V6.chatDocUnsub=db.collection('chats').doc(id).onSnapshot(d=>{const x=d.data()||{},other=(x.memberUids||[]).find(u=>u!==me.uid),typing=document.getElementById('v6Typing');if(typing){const fresh=x.typingUid&&x.typingUid!==me.uid&&x.typingAt?.toDate&&Date.now()-x.typingAt.toDate().getTime()<6000;typing.textContent=fresh?`${userName(x.typingUid)} yazıyor…`:''}const p=document.getElementById('v6PrivatePresence');if(p&&other)p.textContent=lastSeenText(other)});
  };

  let typingTimer=null,lastTyping=0;
  async function signalTyping(){if(!V6.currentChat||Date.now()-lastTyping<1200)return;lastTyping=Date.now();try{await db.collection('chats').doc(V6.currentChat).update({typingUid:me.uid,typingAt:ts()})}catch(_){}clearTimeout(typingTimer);typingTimer=setTimeout(()=>db.collection('chats').doc(V6.currentChat).update({typingUid:null,typingAt:ts()}).catch(()=>{}),3500)}

  async function mountPrivateEnhancements(){const sec=document.getElementById('privateMessages');if(!sec)return;const card=sec.querySelectorAll('.card')[1];if(!card||document.getElementById('v6Typing'))return;const h=card.querySelector('h2');if(h)h.insertAdjacentHTML('afterend','<div id="v6PrivatePresence" class="v6-status"></div><div id="v6Typing" class="v6-typing muted"></div>');const row=card.querySelector('.row');if(row){const mic=document.createElement('button');mic.id='v6Mic';mic.className='btn';mic.textContent='🎙️ Ses';mic.onclick=toggleVoiceRecord;row.appendChild(mic);const inp=document.getElementById('privateChatInput');inp?.addEventListener('input',signalTyping)} }

  async function toggleVoiceRecord(){if(V6.rec){V6.rec.stop();return}if(!V6.currentChat)return alert('Önce bir özel sohbet seç.');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});V6.recStream=stream;const chunks=[];V6.rec=new MediaRecorder(stream);const b=document.getElementById('v6Mic');if(b){b.textContent='⏹️ Bitir';b.classList.add('v6-rec')}V6.rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};V6.rec.onstop=async()=>{clearTimeout(V6.recTimer);stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:V6.rec.mimeType||'audio/webm'});V6.rec=null;if(b){b.textContent='🎙️ Ses';b.classList.remove('v6-rec')}if(blob.size>650000)return alert('Ses kaydı çok büyük. 45 saniyeden kısa kayıt gönder.');const r=new FileReader();r.onload=async()=>{try{await db.collection('chats').doc(V6.currentChat).collection('messages').add({senderUid:me.uid,senderName:me.name||me.email,type:'audio',audioDataUrl:r.result,createdAt:ts()});await db.collection('chats').doc(V6.currentChat).update({updatedAt:ts()})}catch(e){alert('Sesli mesaj gönderilemedi: '+(e.code||e.message))}};r.readAsDataURL(blob)};V6.rec.start();V6.recTimer=setTimeout(()=>V6.rec&&V6.rec.stop(),45000)}catch(e){alert('Mikrofon açılamadı: '+(e.message||e))}}
  window.toggleVoiceRecord=toggleVoiceRecord;

  function rtc(){return new RTCPeerConnection({iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']} ]})}
  async function getMic(){return navigator.mediaDevices.getUserMedia({audio:true,video:false})}
  function showCallModal(title,name,incoming=false){let m=document.getElementById('v6CallModal');if(!m){m=document.createElement('div');m.id='v6CallModal';m.className='v6-call-modal';document.body.appendChild(m)}m.innerHTML=`<div class="v6-call-card"><div class="v6-call-avatar v6-pulse" style="display:grid;place-items:center;background:#6f43dc;font-size:38px;font-weight:900">${esc((name||'A')[0]?.toUpperCase()||'A')}</div><h2>${esc(title)}</h2><div style="font-size:20px;font-weight:800">${esc(name)}</div><div id="v6CallStatus" class="muted" style="margin-top:8px">${incoming?'Gelen sesli arama':'Bağlanıyor…'}</div><div class="v6-call-actions">${incoming?'<button class="btn g" onclick="acceptVoiceCall()">✅ Kabul</button><button class="btn r" onclick="rejectVoiceCall()">❌ Reddet</button>':'<button class="btn r" onclick="endVoiceCall()">📵 Kapat</button>'}</div><audio id="v6RemoteAudio" autoplay></audio></div>`;m.style.display='flex'}
  function hideCallModal(){const m=document.getElementById('v6CallModal');if(m)m.style.display='none'}
  function cleanupCall(){try{V6.pc?.close()}catch(_){}V6.localStream?.getTracks().forEach(t=>t.stop());V6.pc=null;V6.localStream=null;V6.activeCall=null;hideCallModal()}

  window.startVoiceCall=async function(uid){if(uid===me.uid)return;try{const ref=db.collection('calls').doc(),pc=rtc(),stream=await getMic();V6.pc=pc;V6.localStream=stream;V6.activeCall={id:ref.id,ref,otherUid:uid,role:'caller'};stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{const a=document.getElementById('v6RemoteAudio');if(a)a.srcObject=e.streams[0]};pc.onicecandidate=e=>{if(e.candidate)ref.collection('callerCandidates').add(e.candidate.toJSON())};const offer=await pc.createOffer();await pc.setLocalDescription(offer);await ref.set({callerUid:me.uid,callerName:me.name||me.email,calleeUid:uid,calleeName:userName(uid),memberUids:[me.uid,uid],status:'ringing',offer:{type:offer.type,sdp:offer.sdp},startedAt:ts(),updatedAt:ts()});showCallModal('Aranıyor',userName(uid),false);const u1=ref.onSnapshot(async d=>{if(!d.exists)return;const x=d.data();if(x.answer&&!pc.currentRemoteDescription)await pc.setRemoteDescription(new RTCSessionDescription(x.answer));const st=document.getElementById('v6CallStatus');if(st)st.textContent=x.status==='active'?'🔊 Görüşme başladı':x.status==='rejected'?'Arama reddedildi':x.status==='ended'?'Arama bitti':'Çalıyor…';if(['rejected','ended','missed'].includes(x.status)){u1();setTimeout(cleanupCall,600)}});const u2=ref.collection('calleeCandidates').onSnapshot(s=>s.docChanges().forEach(async c=>{if(c.type==='added')try{await pc.addIceCandidate(new RTCIceCandidate(c.doc.data()))}catch(_){}}));V6.callUnsubs.push(u1,u2)}catch(e){cleanupCall();alert('Arama başlatılamadı: '+(e.code||e.message))}};

  function listenIncomingCalls(){unsubs.push(db.collection('calls').where('calleeUid','==',me.uid).where('status','==','ringing').onSnapshot(s=>{const d=s.docs[0];if(!d||V6.activeCall)return;const x=d.data();V6.ring={id:d.id,ref:d.ref,data:x};showCallModal('Gelen Arama',x.callerName||userName(x.callerUid),true)}))}
  window.acceptVoiceCall=async function(){const ring=V6.ring;if(!ring)return;try{const pc=rtc(),stream=await getMic();V6.pc=pc;V6.localStream=stream;V6.activeCall={id:ring.id,ref:ring.ref,otherUid:ring.data.callerUid,role:'callee'};V6.ring=null;stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{const a=document.getElementById('v6RemoteAudio');if(a)a.srcObject=e.streams[0]};pc.onicecandidate=e=>{if(e.candidate)ring.ref.collection('calleeCandidates').add(e.candidate.toJSON())};await pc.setRemoteDescription(new RTCSessionDescription(ring.data.offer));const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await ring.ref.update({answer:{type:answer.type,sdp:answer.sdp},status:'active',answeredAt:ts(),updatedAt:ts()});showCallModal('Görüşme',ring.data.callerName||userName(ring.data.callerUid),false);const u=ring.ref.collection('callerCandidates').onSnapshot(s=>s.docChanges().forEach(async c=>{if(c.type==='added')try{await pc.addIceCandidate(new RTCIceCandidate(c.doc.data()))}catch(_){}}));V6.callUnsubs.push(u)}catch(e){cleanupCall();alert('Arama kabul edilemedi: '+(e.code||e.message))}};
  window.rejectVoiceCall=async function(){if(!V6.ring)return;await V6.ring.ref.update({status:'rejected',endedAt:ts(),updatedAt:ts()}).catch(()=>{});V6.ring=null;hideCallModal()};
  window.endVoiceCall=async function(){const c=V6.activeCall;if(c)await c.ref.update({status:'ended',endedAt:ts(),updatedAt:ts()}).catch(()=>{});cleanupCall()};

  function mountCalls(){const app=document.getElementById('app'),nav=document.getElementById('nav');if(!app||!nav||document.getElementById('v6Calls'))return;const b=document.createElement('button');b.id='v6CallsBtn';b.textContent='📞 Aramalar';b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.sec').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.getElementById('v6Calls').classList.add('on')};nav.appendChild(b);const s=document.createElement('section');s.id='v6Calls';s.className='sec';s.innerHTML='<div class="card"><h2>📞 Sesli Arama Geçmişi</h2><p class="muted">Cevaplanan, reddedilen ve biten çağrılar burada görünür.</p><div id="v6CallList" class="list"></div></div>';app.appendChild(s);let map={};const render=()=>{V6.calls=Object.values(map).sort((a,b)=>(b.startedAt?.seconds||0)-(a.startedAt?.seconds||0));const el=document.getElementById('v6CallList');if(el)el.innerHTML=V6.calls.map(x=>{const out=x.callerUid===me.uid,other=out?x.calleeName:x.callerName;return `<div class="item v6-call-row"><div><b>${out?'↗️':'↙️'} ${esc(other||'Kullanıcı')}</b><div class="muted">${x.startedAt?.toDate?x.startedAt.toDate().toLocaleString('tr-TR'):''} • ${esc(x.status||'')}</div></div><button class="btn s" onclick="startVoiceCall('${out?x.calleeUid:x.callerUid}')">📞 Tekrar Ara</button></div>`}).join('')||'<div class="muted">Henüz çağrı yok.</div>'};const add=snap=>{snap.docs.forEach(d=>map[d.id]={id:d.id,...d.data()});render()};if(isManager()&&me.role==='admin'){unsubs.push(db.collection('calls').orderBy('startedAt','desc').limit(100).onSnapshot(add))}else{unsubs.push(db.collection('calls').where('callerUid','==',me.uid).limit(50).onSnapshot(add));unsubs.push(db.collection('calls').where('calleeUid','==',me.uid).limit(50).onSnapshot(add))}}

  function hookPrivateList(){const oldMountObserver=new MutationObserver(()=>{mountPrivateEnhancements();if(window.privateChats)V6.privateChats=window.privateChats});oldMountObserver.observe(document.body,{childList:true,subtree:true});}

  auth.onAuthStateChanged(u=>{if(!u){clearInterval(window.__v6Presence);return}setTimeout(()=>{injectCss();startPresence();listenIncomingCalls();mountCalls();mountPrivateEnhancements();hookPrivateList();const h=document.querySelector('#app .top h1');if(h)h.textContent='Aura Agency Panel V6 • Live'},1200)});
})();